#!/bin/bash

# Helper script used to generate 
# - application/src/assets/item_category_map.json
# - application/src/assets/localization.json
# - backend/assets/item_ids.txt
# Args: path to directory containing files generated by ao-id-extractor
# Usage python scripts/generate_assets.sh ${EXTRACTED}


declare game_data_dir="$1"

if [[ -z $game_data_dir ]]; then
    echo "First argument should point to game data dir generated by ao-id-extractor"
    exit 1
fi

declare items_file="$(find $game_data_dir -type f -name items.xml)"
declare localization_file="$(find $game_data_dir -type f -name localization.xml)"

if [[ -z $items_file ]]; then
    echo "$game_data_dir does not contains items.xml file"
    exit 1
fi

if [[ -z $localization_file ]]; then
    echo "$localization_file does not contains localization.xml file"
    exit 1
fi

echo "Generating application/src/assets/item_category_map.json..."
python scripts/item_category_map.py $items_file | python -m json.tool > application/src/assets/item_category_map.json

echo "Generating application/src/assets/localization.json..."
python scripts/localization.py $localization_file | python -m json.tool > application/src/assets/localization.json

echo "Generating backend/assets/item_ids.txt..."
python scripts/item_id.py $items_file > backend/assets/item_ids.txt